### ISSUE TITLE
adding a new table to schema.prisma doesn't make it accessible though ctx.prisma.tableName

### ISSUE THREAD

**Issue by abdoo9** [bot-base/telegram-bot-template#125]
when I added a new table to Prisma schema and `npx generate` and migrate
the new table was not accessible through `ctx.prisma.newTableName` in the `language.keyboard.ts` file! typescript compiles normally but the runtime gives the error that the property `newTableName` is undefied

**Comment by deptyped** [comment]
Hello, can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by abdoo9** [comment]
my bad I was writing the wrong table name
