### ISSUE TITLE
How to multiple web app and bot ?

### ISSUE THREAD

**Issue by Kinghood15** [bot-base/telegram-bot-template#306]
I don't know how to configure the env so I can run the web app and bot at the same time because your env is asking for a link. So I will have to build a separate web app to have the url link. Is there any way you can code 2 at the same time on your computer?

**Comment by deptyped** [comment]
Hi. I'm not sure if I understood your problem correctly. Web app needs to have a link to open it in Telegram. So you need to first run the web app (`npm run dev` in the `webapp/` directory) to get the link, then set the link in .env and run the bot (`npm run dev` in the root directory). This way you will have both the web app and the bot running on your computer at the same time.

**Comment by deptyped** [comment]
You don't need to build and deploy web app in development mode, you can use tunneling software as described in [step 3](https://github.com/bot-base/telegram-bot-template/tree/example/webapp/webapp#development-mode).
