### ISSUE TITLE
'env-schema' usage in your template for config validation

### ISSUE THREAD

**Issue by kuslosolodka** [bot-base/telegram-bot-template#353]
What do you think about [env-schema](https://github.com/fastify/env-schema) package for config validation from fastify? 

I guess it'll be a good addition to your template because you are using fastify

**Comment by deptyped** [comment]
Hi, I don't want to tie the template to an ecosystem of a particular web server. 

Some people may prefer an alternative web server (or runtime, such as Deno, which Fastify does not support), and some may choose not to use a web server at all and prefer polling mode instead. Currently, migration is pretty simple, but this change will make it more complicated. Thank you for the suggestion!
