### ISSUE TITLE
Ask about the api and crud section on the branch example/prisma

### ISSUE THREAD

**Issue by Kinghood15** [bot-base/telegram-bot-template#484]
In the branch example/prisma, can you give a more specific example? Like a bot typing the /start command will automatically add new users to the database, for example. And if I want to write a separate API for the web app, can I use it?

**Comment by deptyped** [comment]
Hi!

> Like a bot typing the /start command will automatically add new users to the database, for example.

It's pretty simple to implement, just add a query to the /start handler:

```diff
feature.command('start', logHandle('command-start'), async (ctx) => {
+ await ctx.prisma.user.upsert({
+   where: {
+     telegramId: ctx.from.id,
+   },
+   create: {
+     telegramId: ctx.from.id,
+   },
+   update: {
+   },
+ })
  return ctx.reply(ctx.t('welcome'))
})
```

Also, grammY has better ways to accomplish this, like [the chat-members plugin](https://grammy.dev/plugins/chat-members) with [Prisma storage adapter](https://github.com/grammyjs/storages/tree/main/packages/prisma).

> And if I want to write a separate API for the web app, can I use it?

Yes, the template uses [Hono](https://hono.dev/) framework and it's great for creating APIs:
https://hono.dev/guides/examples#web-api
