### ISSUE TITLE
how to handle pre_checkout_query ?

### ISSUE THREAD

**Issue by jiangsi** [bot-base/telegram-bot-template#534]
when I handle the event of pre_checkout_query

there is an err show ,"Cannot access session "

```
    err: {
      "type": "Error",
      "message": "Cannot access session data because this update does not belong to a chat, so the session key is undefined!",
      "stack":
          Error: Cannot access session data because this update does not belong to a chat, so the session key is undefined!
              at get (E:\web\bothono\node_modules\grammy\out\convenience\session.js:201:31)
              at <anonymous> (E:\web\bothono\node_modules\@grammyjs\i18n\script\src\i18n.js:116:39)
              at processTicksAndRejections (:12:39)
      "originalLine": 86,
      "originalColumn": 28
    }

```

**then ,I put the handle function near the bot Constructor function , but I think this is not best solution for this type of callback handler. 
Can you give some advice on this? ,thanks
**

`export function createBot(token: string, options: Options = {}) {
  const { sessionStorage } = options;
  const bot = new TelegramBot(token, {
    ...options.config,
    ContextConstructor: createContextConstructor({ logger }),
  });

  bot.on("pre_checkout_query", async (ctx) => {
    try {
      // handle pre_checkout_query，do not use ctx.session
      console.log("------ pre_checkout_query --------");
      await ctx.answerPreCheckoutQuery(true);
      console.log("------pre_checkout_query success--------");
      return;
    } catch (error) {
      console.error("handle  pre_checkout_query :", error);
      return;
    }
  });
`

**Comment by deptyped** [comment]
Pre-checkout query does not belong to a chat (`ctx.chat` is `undefined`), so the default session key resolver will not work. You need to specify a custom `getSessionKey` function:
https://grammy.dev/plugins/session.html#session-keys
