### ISSUE TITLE
Docs: How to add `.row()` to `InlineKeyboard.from`?

### ISSUE THREAD

**Issue by mrienstra** [bot-base/telegram-bot-template#549]
[`src/bot/keyboards/change-language.ts`](https://github.com/bot-base/telegram-bot-template/blob/ed45843/src/bot/keyboards/change-language.ts#L17-L28) (and [`src/bot/features/language.ts`](https://github.com/bot-base/telegram-bot-template/blob/ed45843/src/bot/features/language.ts)) show a very nice way of making an `InlineKeyboard` and handling `callbackQuery`, but I can't work out how to use `.row()` with this pattern.

I took a look at https://grammy.dev/plugins/keyboard#inline-keyboards and tried a few things.

I have a work-around, but obviously it's not as elegant:

```ts
  return new InlineKeyboard()
    .text(getLabel(i18n.locales[0]), `language:${i18n.locales[0]}`).row()
    .text(getLabel(i18n.locales[1]), `language:${i18n.locales[1]}`)
```

**Comment by deptyped** [comment]
Hi! `InlineKeyboard.from` is an alternative style for building keyboards from arrays, you can't use `.row()` here.
`InlineKeyboard.from` takes a 2-dimension array as an argument, so the equivalent code looks like this:
```ts
return InlineKeyboard.from([
  [InlineKeyboard.text(getLabel(i18n.locales[0]), `language:${i18n.locales[0]}`)], // row 1
  [InlineKeyboard.text(getLabel(i18n.locales[1]), `language:${i18n.locales[1]}`)], // row 2
  // each array in the root array represents a row
])
```
Your code is fine, both ways are equally good, just different styles.

**Comment by mrienstra** [comment]
Thanks @deptyped! Well, the downside of what I came up: requires hardcoding the length. But for many use-cases, that's not an issue..
